export enum Variant {
  primary = "primary",
  secondaryDark = "secondaryDark",
  secondaryLight = "secondaryLight",
}
export enum BackgroundColor {
  "black" = `bg-black`,
  "transparent" = `bg-transparent`,
  "blue-98" = `bg-blue-98`,
  "blue-92" = `bg-blue-92`,
  "blue-86" = `bg-blue-86`,
  "blue-61" = `bg-blue-61`,
  "blue-37" = `bg-blue-37`,
  "blue-19" = `bg-blue-19`,
  "red-98" = `bg-red-98`,
  "red-92" = `bg-red-92`,
  "red-86" = `bg-red-86`,
  "red-61" = `bg-red-61`,
  "red-37" = `bg-red-37`,
  "red-19" = `bg-red-19`,
  "yellow-98" = `bg-yellow-98`,
  "yellow-92" = `bg-yellow-92`,
  "yellow-86" = `bg-yellow-86`,
  "yellow-61" = `bg-yellow-61`,
  "yellow-37" = `bg-yellow-37`,
  "yellow-19" = `bg-yellow-19`,
}
export enum TextColor {
  "black" = `text-black`,
  "transparent" = `text-transparent`,
  "blue-98" = `text-blue-98`,
  "blue-92" = `text-blue-92`,
  "blue-86" = `text-blue-86`,
  "blue-61" = `text-blue-61`,
  "blue-37" = `text-blue-37`,
  "blue-19" = `text-blue-19`,
  "red-98" = `text-red-98`,
  "red-92" = `text-red-92`,
  "red-86" = `text-red-86`,
  "red-61" = `text-red-61`,
  "red-37" = `text-red-37`,
  "red-19" = `text-red-19`,
  "yellow-98" = `text-yellow-98`,
  "yellow-92" = `text-yellow-92`,
  "yellow-86" = `text-yellow-86`,
  "yellow-61" = `text-yellow-61`,
  "yellow-37" = `text-yellow-37`,
  "yellow-19" = `text-yellow-19`,
}
export enum BorderColor {
  "black" = `border-black`,
  "transparent" = `border-transparent`,
  "blue-98" = `border-blue-98`,
  "blue-92" = `border-blue-92`,
  "blue-86" = `border-blue-86`,
  "blue-61" = `border-blue-61`,
  "blue-37" = `border-blue-37`,
  "blue-19" = `border-blue-19`,
  "red-98" = `border-red-98`,
  "red-92" = `border-red-92`,
  "red-86" = `border-red-86`,
  "red-61" = `border-red-61`,
  "red-37" = `border-red-37`,
  "red-19" = `border-red-19`,
  "yellow-98" = `border-yellow-98`,
  "yellow-92" = `border-yellow-92`,
  "yellow-86" = `border-yellow-86`,
  "yellow-61" = `border-yellow-61`,
  "yellow-37" = `border-yellow-37`,
  "yellow-19" = `border-yellow-19`,
}
export enum HoverBackgroundColor {
  "disabled" = "disabled",
  "black" = `hover:bg-black`,
  "transparent" = `hover:bg-transparent`,
  "blue-98" = `hover:bg-blue-98`,
  "blue-92" = `hover:bg-blue-92`,
  "blue-86" = `hover:bg-blue-86`,
  "blue-61" = `hover:bg-blue-61`,
  "blue-37" = `hover:bg-blue-37`,
  "blue-19" = `hover:bg-blue-19`,
  "red-98" = `hover:bg-red-98`,
  "red-92" = `hover:bg-red-92`,
  "red-86" = `hover:bg-red-86`,
  "red-61" = `hover:bg-red-61`,
  "red-37" = `hover:bg-red-37`,
  "red-19" = `hover:bg-red-19`,
  "yellow-98" = `hover:bg-yellow-98`,
  "yellow-92" = `hover:bg-yellow-92`,
  "yellow-86" = `hover:bg-yellow-86`,
  "yellow-61" = `hover:bg-yellow-61`,
  "yellow-37" = `hover:bg-yellow-37`,
  "yellow-19" = `hover:bg-yellow-19`,
}
export enum HoverTextColor {
  "disabled" = "disabled",
  "black" = `hover:text-black`,
  "transparent" = `hover:text-transparent`,
  "blue-98" = `hover:text-blue-98`,
  "blue-92" = `hover:text-blue-92`,
  "blue-86" = `hover:text-blue-86`,
  "blue-61" = `hover:text-blue-61`,
  "blue-37" = `hover:text-blue-37`,
  "blue-19" = `hover:text-blue-19`,
  "red-98" = `hover:text-red-98`,
  "red-92" = `hover:text-red-92`,
  "red-86" = `hover:text-red-86`,
  "red-61" = `hover:text-red-61`,
  "red-37" = `hover:text-red-37`,
  "red-19" = `hover:text-red-19`,
  "yellow-98" = `hover:text-yellow-98`,
  "yellow-92" = `hover:text-yellow-92`,
  "yellow-86" = `hover:text-yellow-86`,
  "yellow-61" = `hover:text-yellow-61`,
  "yellow-37" = `hover:text-yellow-37`,
  "yellow-19" = `hover:text-yellow-19`,
}
export enum Size {
  small = "small",
  medium = "medium",
  large = "large",
}
